DATASET: vrd_wiki_and_node2vec
NUM_DEVICES: 8
MODEL:
  TYPE: VGG16_reldn_fast_rcnn_conv4_spo_for_p
  SUBTYPE: embd_fusion_w_relu_yall
  SPECS: 8gpus_vgg16_softmaxed_triplet_no_last_l2norm_7_epochs_trainval_w_cluster_norm_scalar_3
  LOSS_TYPE: SOFTMAXED_TRIPLET  # EUC, SOFTMAX
  MODEL_NAME: VGG16_rel_softmaxed_triplet
  BN_MOMENTUM: 0.9
  BN_EPSILON: 1.0000001e-5
  FC_INIT_STD: 0.01
  ALLOW_INPLACE_SUM: True
  MEMONGER: True
VISUAL_EMBEDDING:
  WEIGHT_SHARING: SBJ_OBJ_SHARED #, all_unshared,  sbj_obj_shared, all_unshared
  L2_NORMALIZE: True
TEXT_EMBEDDING:
  HIDDEN_LAYERS: 1  # 1, 0
  L2_NORMALIZE: True
INPUT_LANG_EMBEDDING_DIM: 600
OUTPUT_EMBEDDING_DIM: 1024
TRAIN:
  PARAMS_FILE: datasets/large_scale_VRD/coco_models/vgg16_model_final.pkl
  DATA_TYPE: train
  BBOX_REG: False
  BBOX_NORMALIZE_TARGETS: False  # No bbox regression at the end
  USE_FLIPPED: True
  BATCH_SIZE_PER_IM: 128
  FG_FRACTION: 0.25
  FG_THRESH: 0.5
  NORM_SCALAR: 3.0
  # since we train over 2 nodes, so evaluation frequency is 2 times frequent
  # IN1k train data has 1281167 images, so 1 epoch = 1281167 / (256 * 2)
  # since we train over 1 node with 8 gpus per node,
  # evaluation frequency is 1 times frequent
  # VRD train data has 3780 * 2 (with flipped rois) images,
  # so 1 epoch = 3780 * 2 / (8 * 1)
  EVALUATION_FREQUENCY: 95  # evaluate for every ~0.1 epoch
TEST:
  WEIGHTS: checkpoints/vrd_wiki_and_node2vec/latest_final.pkl
  DATA_TYPE: test
  PROPOSAL_FILE: datasets/large_scale_VRD/proposals/vrd/test/aug_pairwise_boxes_11.pkl
  BBOX_REG: False
SOLVER:
  BASE_LR: 0.001
  STEP_SIZES: [5670]
  NUM_ITERATIONS: 6615
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BN: 0.0
  MOMENTUM: 0.9
  GAMMA: 0.1
  NESTEROV: True
  WARM_UP_ITERS: 100
  WARM_UP_LR: 0.0001
CHECKPOINT:
  CHECKPOINT_PERIOD: 945
METRICS:
  EVALUATE_FIRST_N_WAYS: False
